.POSIX:
MOSMLC=mosmlc -orthodox

all: MkTable.sml

### Table-related rules
ORD-sig.ui:
	$(MOSMLC) -c -toplevel ORD-sig.sml

Table-sig.ui: ORD-sig.ui
	$(MOSMLC) -c -toplevel $^ Table-sig.sml

MkTable.sml: ORD-sig.ui Table-sig.ui
	$(MOSMLC) -c -toplevel $^ $@

clean:
	rm -rf *.ui *.uo
